# Generated by Django 5.0 on 2024-01-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='beer_decription',
            field=models.CharField(max_length=400),
        ),
    ]
