# Generated by Django 5.0 on 2024-07-21 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_alter_beer_beer_decription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='beer_decription',
            new_name='beer_description',
        ),
        migrations.AddField(
            model_name='beer',
            name='beer_link',
            field=models.CharField(default='NO LINK', max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
