# Generated by Django 5.0 on 2024-07-29 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0003_rename_beer_decription_beer_beer_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_text',
            field=models.CharField(default='No review', max_length=200),
        ),
        migrations.AlterField(
            model_name='beer',
            name='author',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='beer',
            name='beer_country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='beer',
            name='beer_description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='beer',
            name='beer_label',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='beer',
            name='beer_link',
            field=models.CharField(default='https://www.alko.fi', max_length=100),
        ),
        migrations.AlterField(
            model_name='beer',
            name='beer_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
